maintainer       "Luke Randall"
maintainer_email "luke.randall@gmail.com"
license          "MIT"
description      "Sets up user preferences"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.2"
depends          "zsh"
depends          "git"
depends          "rbenv"
depends          "ruby_build"
